version: "3.7"

services:
  rabbit:
    image: rabbitmq:3.6.6-management
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user

  app:
    build: .
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - rabbit

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev

  producer:
    build:
      context: ./communication
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    depends_on:
      - rabbit

  consumer:
    build:
      context: ./receive
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    restart: on-failure
    depends_on:
      - rabbit
    links:
      - rabbit
      - db

volumes:
  postgres_data:
